@startuml
header @author: Chandu D , @created on: 2022/10/23
!theme amiga
footer  Page %page% of %lastpage%
title  Error Detection, Analysis and Reporting

skinparam {
'actorStyle awesome
'monochrome reverse
SequenceMessageAlignment direction
}

actor "Perf_Engineer" as devUser
participant "Service-Portal" as servicePortal
participant "Jira-Reporting-Service" as jiraReportingService
database  "Issue DB" as issueQueue
participant "Data-Analyzer-Service" as dataAnalyzerService
participant "Splunk-DataMining-Service" as dataMiningService
database "Data-Lake(Mongo-DB)" as db
entity "Splunk-Server" as splunk

group Step: Data-mining from Splunk
splunk -> dataMiningService ++ : POST /api/post/postData \n To respective Kafka-Queue(Webhook).
dataMiningService -> db ++ : Authenticate service
db-> db: Validate \n DB-service Key
db -[#green]> dataMiningService  : Success, Token Validated
dataMiningService -> db  : saves data
db -[#green]> dataMiningService  -- : Operation Success
dataMiningService -[#green]> splunk -- : return \nhttp StatusCode(200)
else on ERROR
db -[#red]> dataMiningService ++ : transmits error codes
dataMiningService -> dataMiningService : exceptions/errors \nlogged
dataMiningService -[#red]> splunk -- : return \nhttp StatusCode(401/501)
end

group Step : Data Analysis
    group Step: Issue Identification
    dataMiningService -> dataAnalyzerService ++: data send to analyzer queue
    dataAnalyzerService -> dataAnalyzerService : pattern-detection &\nclassification
    dataAnalyzerService -> issueQueue --: post to issue-queue
    end
    group Step: Issue Creation


    end
end

group Step: Review Generated Defects
devUser -> servicePortal ++ : Login
servicePortal -> servicePortal : validate\ntoken
servicePortal -[#green]> devUser : success
devUser -[#green]> servicePortal : authenticated
devUser -> servicePortal :validates the defects
servicePortal -> servicePortal ++ : defects updated as required
jiraReportingService -> issueQueue ++ : issue DB updated
issueQueue -> jiraReportingService --: update successful
servicePortal -> SF_JiraPortal ++: post valid JIRA-defects
SF_JiraPortal -[#green]> devUser --: http-201-defect-created
servicePortal -[#green]> devUser --: logout
end
@enduml