########################## NOTES ###############################################
### - Don't run application in 'default' profile. This file is the default config.
### - Use dev profile for local development.

########################## Default Configurations ##############################
### Server #####################################################################
server:
  port: 8851
  servlet:
    context-path: /svc/ingestion
### Application ################################################################

spring:
#  kafka:
#      bootstrap-servers: ${kafka_bootstrap_servers:localhost:29092}
#      properties:
#        sasl:
#          jaas:
#            config: org.apache.kafka.common.security.plain.PlainLoginModule required username=admin password=password;
#          mechanism: PLAIN
#        security:
#          protocol: PLAINTEXT
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      username: admin
      password: password
      database: perflogglobaldb
      port: 27017
      host: localhost
  application:
    name: pinnacle-data-ingestion

  #  jackson:
#    serialization:
#      FAIL_ON_EMPTY_BEANS: false
  jpa:
    open-in-view: false
###mongo collections#
mongodb:
  collections:
    perf-logs:
      dwr-suffix: dwr


### Kafka ################################################################
kafka:
    bootstrapAddress : localhost:9092 # kafka bootstrap server
    groupId : perf-log-api-consumer
    jaas : org.apache.kafka.common.security.plain.PlainLoginModule required username=admin password=password;
    security: PLAINTEXT
### Actuator    ################################################################
management:
  endpoint:
    health:
      probes:
        enabled: false
