########################## NOTES ###############################################
### - Don't run application in 'default' profile. This file is the default config.
### - Use dev profile for local development.

########################## Default Configurations ##############################
### Server #####################################################################
server:
  port: 8852
  servlet:
    context-path: /svc/analyzer
### Spring App properties ################################################################
spring:
  application:
    name: pinnacle-data-analyzer
  ###### DB connection config ####################################################
  dataSource:
    url: jdbc:postgresql://localhost:5432/pinnacle-global-db
    username: user
    password: pwd123
  ###### JPA properties ##########################################################
  jpa:
    hibernate:
      ddl-auto: update  # TODO: production should be validate only.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        se_sql_comments: false
        format_sql: true
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true
      javax:
        persistence:
          validation:
            mode: none
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  data:
###### Spring app MONGO-DB properties#######################################
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      username: admin
      password: password
      database: perflogglobaldb
      port: 27017
      host: localhost
###MONGO-DB collections#######################################
mongodb:
  collections:
    perf-logs:
      dwr-suffix: dwr
### Kafka ################################################################
kafka:
    bootstrapAddress : localhost:9092 # kafka bootstrap server
    groupId : perf-log-api-consumer
    jaas : org.apache.kafka.common.security.plain.PlainLoginModule required username=admin password=password;
    security: PLAINTEXT
### Constants ##################################################################
constants:
  services:
    gateway:
      url: http://localhost:8881
### Actuator    ################################################################
management:
  endpoint:
    health:
      probes:
        enabled: false
