constants:
  security:
    apis:
      login: ""
      token: ""
      signup: ""
      actuator: "/actuator/**"
    jwt:
      secret: "e09T6J#1V5bYi4E*oXs55uDpB7S3ZB6rn3ab@n568b7D4Ugj1I7OJn3xjri89Ro#"
      expiration-time-seconds: "604800"
      token-type: "Bearer"
  svc:
    ingestion:
      uri: &svc-ingestion-uri http://localhost:8851
    
server:
  port: 8881
spring:
  application:
  name: pinnacle-gateway
  cloud:
    config:
      import-check:
        enabled: false
    gateway:
      enabled: true # default value after including starter gateway dependency. Should we expose this through admin/api to quickly shut off gateway ??
      routes:
        # Pinnacle ingestion service routes ######################################
        - id: pinnacle-ingestion
          uri: *svc-ingestion-uri
          predicates:
            - Path=/svc/ingestion/**
#          filters:
#            - StripPrefix=1
#            - PrefixPath=/svc
### Actuator    ################################################################
management:
  endpoint:
    health:
      probes:
        enabled: true


