@startuml
header
    auhor : i861116, date: 10/15/2021
endheader
title Data Analyzer

footer

endfooter

actor Drool_Rule_Engine as pg_db
actor Mongo_DB as db

rectangle  Power-BI {
    usecase Drool_Engine_Service   as drool_engine_svc
    usecase Data_Fetch_Service as fetch_data
    usecase Data_Parsing_Engine as data_parser
    usecase Anomaly_Detector as anomaly_detector
}

left to right direction
db <-- fetch_data: get
fetch_data ..> data_parser : <<push>>
data_parser <.. anomaly_detector : <<uses>>
drool_engine_svc <.. anomaly_detector : <<uses>>
anomaly_detector --> pg_db:publishes
@enduml